name: Tag versions

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install toml-cli

      - name: Extract version from pyproject.toml
        id: get_version
        run: echo "VERSION=$(toml get pyproject.toml project.version | tr -d '\"')" >> $GITHUB_ENV


      - name: Check if tag exists
        id: check_tag
        run: |
          echo "CHECK_TAG=$(git tag -l "v${{ env.VERSION }}")" >> $GITHUB_ENV
          if [[ "$(git tag -l "v${{ env.VERSION }}")" ]]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Tag new version
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"
